Changed error messages to spanish
LuisPalominoTrevilla/Guessit-back pull request #20
Opened 2019-04-21 22:21 UTC by JorgePS14

Register error messages are now in spanish

2019-04-22 02:26 UTC, LuisPalominoTrevilla requested changes
Falta cambiar mensajes a español de los otros endpoints

2019-04-22 04:29 UTC, JorgePS14 commented
Quieres que cambie lo que se imprime en consola?

2019-04-22 04:42 UTC, LuisPalominoTrevilla commented
> Quieres que cambie lo que se imprime en consola?

los fmt.FPrintf no imprimen en consola, son la respuesta

2019-04-22 04:49 UTC, JorgePS14 commented
Listo.

2019-04-23 05:38 UTC, LuisPalominoTrevilla approved these changes

2019-04-24 16:29 UTC, merged